export const curiosities = [
  "A primeira máquina de calcular foi criada por Blaise Pascal em 1642.",
  "O primeiro bug de computador foi um inseto preso em um relé do Mark II em 1947.",
  "O ENIAC, primeiro computador eletrônico, pesava cerca de 27 toneladas.",
  "O teclado QWERTY foi projetado para evitar que as teclas das máquinas de escrever travassem.",
  "O primeiro domínio da web registrado foi symbolics.com, em 1985.",
  "O primeiro e-mail da história foi enviado por Ray Tomlinson em 1971.",
  "O termo 'computador' originalmente se referia a pessoas que faziam cálculos manualmente.",
  "O código de programação mais antigo ainda em uso é COBOL, criado em 1959.",
  "O primeiro mouse de computador era de madeira e foi inventado por Douglas Engelbart em 1964.",
  "O Windows XP ainda é usado em alguns sistemas críticos, como caixas eletrônicos.",
  "A senha '123456' ainda é uma das mais usadas no mundo, e também uma das mais inseguras.",
  "O primeiro site da história ainda está no ar: info.cern.ch.",
  "Os primeiros disquetes tinham apenas 80 KB de capacidade.",
  "O primeiro HD, criado pela IBM em 1956, tinha 5 MB e pesava mais de uma tonelada.",
  "O primeiro vírus de computador para MS-DOS se chamava Brain e surgiu em 1986.",
  "A internet surgiu como ARPANET, um projeto militar dos EUA na década de 1960.",
  "O primeiro jogo de computador foi Spacewar!, criado em 1962 no MIT.",
  "A primeira versão do Windows foi lançada em 1985.",
  "O primeiro processador comercial foi o Intel 4004, lançado em 1971.",
  "A linguagem Python foi criada por Guido van Rossum em 1991.",
  "A linguagem de programação mais antiga ainda em uso é Fortran, criada em 1957.",
  "A Wikipédia foi lançada em 2001 e hoje é uma das maiores fontes de conhecimento online.",
  "A Deep Blue, da IBM, venceu o campeão mundial de xadrez Garry Kasparov em 1997.",
  "O Google começou como um projeto de pesquisa em Stanford em 1996.",
  "O primeiro smartphone foi o IBM Simon, lançado em 1992.",
  "A Apple foi fundada em 1976 por Steve Jobs, Steve Wozniak e Ronald Wayne.",
  "A primeira mensagem de texto (SMS) foi enviada em 1992.",
  "A primeira loja online surgiu em 1994: NetMarket.",
  "O primeiro tweet da história foi 'just setting up my twttr' em 2006.",
  "O primeiro sistema operacional da Microsoft foi o MS-DOS.",
  "O primeiro site de redes sociais foi o SixDegrees, lançado em 1997.",
  "A primeira webcam foi usada para monitorar uma cafeteira no laboratório da Universidade de Cambridge.",
  "O primeiro emoticon foi criado em 1982 por Scott Fahlman.",
  "O nome 'Bluetooth' vem de um rei viking do século X.",
  "O primeiro chip de computador foi inventado por Jack Kilby em 1958.",
  "O primeiro computador pessoal foi o Altair 8800, lançado em 1975.",
  "O primeiro supercomputador foi o CDC 6600, lançado em 1964.",
  "A palavra 'Google' vem do termo matemático 'googol', que significa 1 seguido de 100 zeros.",
  "O primeiro vídeo do YouTube foi postado em 2005 e se chama 'Me at the zoo'.",
  "O primeiro sistema de armazenamento em nuvem foi o Amazon S3, lançado em 2006.",
  "Os emojis foram criados no Japão em 1999.",
  "O primeiro navegador web foi o WorldWideWeb, criado por Tim Berners-Lee em 1990.",
  "A tecnologia Wi-Fi foi inventada por acidente na Austrália em 1992.",
  "A Apple quase faliu nos anos 90 antes do retorno de Steve Jobs.",
  "O código de barras foi inventado antes dos computadores, em 1949.",
  "O primeiro computador brasileiro foi o Patinho Feio, construído em 1972.",
  "O Google processa mais de 3,5 bilhões de pesquisas por dia.",
  "O primeiro bug registrado em software foi encontrado por Grace Hopper.",
  "O computador quântico do Google já realizou cálculos impossíveis para computadores clássicos.",
  "A primeira inteligência artificial foi desenvolvida na década de 1950.",
  "Os primeiros chips ARM foram usados em calculadoras.",
  "A computação em nuvem só se popularizou na década de 2010.",
  "Os algoritmos de machine learning se baseiam em conceitos matemáticos da década de 1940.",
  "A primeira impressora 3D foi criada em 1983.",
  "O primeiro videogame caseiro foi o Magnavox Odyssey, lançado em 1972.",
  "O primeiro sistema operacional Unix foi desenvolvido em 1969.",
  "A primeira venda online foi um CD de Sting em 1994.",
  "O primeiro tablet da história foi lançado em 1989, chamado GRiDPad.",
  "O Facebook foi criado em 2004 e se chamava 'TheFacebook'.",
  "O primeiro comercial da Apple para o Macintosh foi dirigido por Ridley Scott.",
  "O primeiro celular com câmera foi lançado em 1999 no Japão.",
  "A primeira transmissão ao vivo da internet foi feita em 1993.",
  "O primeiro trojan da história se chamava 'ANIMAL' e foi criado em 1975.",
  "O WhatsApp foi lançado em 2009 por ex-funcionários do Yahoo.",
  "O primeiro drone controlado por computador foi desenvolvido na década de 1970.",
  "O primeiro e-commerce brasileiro foi o Submarino, lançado em 1999.",
  "A Wikipédia foi inspirada na enciclopédia Encarta, da Microsoft.",
  "O primeiro processador com mais de um núcleo foi lançado em 2001.",
  "O primeiro computador pessoal com interface gráfica foi o Xerox Alto.",
  "O termo 'firewall' vem da construção civil, onde significa uma parede à prova de fogo.",
  "O primeiro aplicativo de mensagens instantâneas foi o ICQ, lançado em 1996.",
  "A primeira foto postada no Instagram foi tirada por Kevin Systrom, um dos fundadores.",
  "O primeiro HD de 1 TB foi lançado em 2007.",
  "A primeira versão do Linux foi lançada em 1991 por Linus Torvalds.",
  "A tecnologia de reconhecimento facial já existia nos anos 1960.",
  "O processador mais rápido do mundo atualmente pertence à IBM.",
  "O primeiro podcast foi lançado em 2004.",
  "O primeiro site de vídeos antes do YouTube foi o iFilm.",
  "O primeiro comercial de TV sobre computadores foi feito pela Apple.",
  "Os primeiros computadores usavam válvulas em vez de transistores.",
  "A primeira IA a vencer um humano no xadrez foi o Deep Blue em 1997.",
  "O primeiro hack documentado ocorreu na década de 1960 no MIT.",
  "O primeiro banco de dados relacional foi criado por Edgar Codd nos anos 1970.",
  "A internet das coisas (IoT) foi proposta em 1999.",
  "O primeiro antivírus comercial foi o McAfee, lançado nos anos 1980.",
  "O primeiro computador com processador 64 bits foi o AMD Athlon 64, lançado em 2003.",
  "O primeiro site de comércio eletrônico foi o Amazon, lançado em 1994.",
  "O primeiro computador com processador Intel Core foi o iMac G5, lançado em 2002.",
  "O primeiro site de vídeos comerciais foi o YouTube, lançado em 2005.",
  "O primeiro computador com processador ARM foi o Apple Newton, lançado em 1993.",
  "O primeiro computador com processador AMD foi o AMD K6, lançado em 1997.",
  "O primeiro computador com processador Intel Atom foi o Atom N270, lançado em 2008.",
  "O primeiro computador com processador Intel Core i7 foi o Core i7-920, lançado em 2009.",
  "O primeiro computador com processador Intel Core i9 foi o Core i9-9900K, lançado em 2019.",
  "O primeiro computador com processador Intel Core i10 foi o Core i10-12900K, lançado em 2021.",
  "O primeiro computador com processador Intel Core i11 foi o Core i11-13900K, lançado em 2022.",
  "O primeiro computador com processador Intel Core i12 foi o Core i12-14900K, lançado em 2023.",
  "O primeiro computador com processador Intel Core i13 foi o Core i13-15900K, lançado em 2024.",
  "O primeiro computador com processador Intel Core i14 foi o Core i14-16900K, lançado em 2025.",
  "O primeiro computador com processador Intel Core i15 foi o Core i15-17900K, lançado em 2026.",
  "O primeiro computador com processador Intel Core i16 foi o Core i16-18900K, lançado em 2027.",
  "O primeiro mouse de computador foi feito de madeira em 1964.",
  "O termo 'bug' surgiu quando um inseto causou problemas em um computador em 1947.",
  "O primeiro email spam foi enviado em 1978.",
  "O símbolo @ foi escolhido para emails por ser pouco usado na época.",
  "O primeiro vírus de computador foi criado em 1971 como um experimento.",
  "A primeira senha digital tinha apenas 4 caracteres em 1961.",
  "O primeiro smartphone foi o IBM Simon, lançado em 1994.",
  "O código QR foi inventado em 1994 para rastrear peças automotivas.",
  "O primeiro tweet foi enviado por Jack Dorsey em 2006.",
  "O Google começou como um projeto universitário chamado 'BackRub'.",
  "O primeiro domínio .com registrado foi symbolics.com em 1985.",
  "A primeira webcam foi criada para monitorar uma cafeteira.",
  "O primeiro SSD comercial foi lançado pela SanDisk em 1991.",
  "O Bluetooth foi nomeado após um rei viking do século X.",
  "O primeiro CD-ROM podia armazenar 550 MB de dados.",
  "A primeira conexão Wi-Fi foi chamada de ALOHAnet em 1971.",
  "O termo 'podcast' combina iPod com broadcast.",
  "O primeiro upload no YouTube foi no zoológico em 2005.",
  "A linguagem Python foi nomeada por causa do Monty Python.",
  "O primeiro emoji foi criado no Japão em 1999.",
  "O ENIAC, primeiro computador eletrônico de grande escala, pesava 30 toneladas.",
  "Ada Lovelace é considerada a primeira programadora da história.",
  "O primeiro computador pessoal, o Altair 8800, foi lançado em 1975.",
  "A primeira programadora a trabalhar com o ENIAC foi Grace Hopper.",
  "O primeiro jogo de computador foi 'Spacewar!', criado em 1962.",
  "O primeiro processador Intel, o 4004, tinha apenas 2300 transistores.",
  "A World Wide Web foi criada por Tim Berners-Lee em 1989.",
  "O primeiro laptop comercial foi o Osborne 1, lançado em 1981.",
  "O primeiro teclado QWERTY foi criado em 1868 para máquinas de escrever.",
  "O primeiro programa de computador foi escrito por Ada Lovelace em 1842.",
  "O primeiro vírus para MS-DOS, o Brain, surgiu em 1986.",
  "A primeira versão do Windows foi lançada em 1985.",
  "O primeiro navegador web popular foi o Mosaic, lançado em 1993.",
  "A primeira linguagem de programação de alto nível foi o Fortran em 1957.",
  "O primeiro microprocessador comercial foi o Intel 4004, lançado em 1971.",
  "O primeiro disco rígido comercial foi lançado pela IBM em 1956.",
  "O primeiro modem comercial foi lançado em 1962.",
  "O primeiro mouse comercial foi lançado pela Xerox em 1973.",
  "O primeiro computador Apple foi vendido por $666,66 em 1976.",
  "O primeiro processador dual-core foi lançado pela IBM em 2001.",
];
